name: Get daily availability

on:
  schedule:
    - cron:  '0 8 * * *'
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Update pip and poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install Python dependencies
        run: poetry install
      - name: Get new availability data
        run: |
          poetry run python scripts/get_availability.py --out daily/$(date +%Y-%m-%d).csv
      - name: Commit and push to availability branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'leonlan@users.noreply.github.com'
          git fetch origin
          git checkout availability
          git add daily/$(date +%Y-%m-%d).csv
          git commit -m "Add availability $(date +%Y-%m-%d)"
          git push origin availability
