name: Get daily availability

on:
  schedule:
    - cron:  '0 */1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.27"

      - name: Install Python version
        run: uv python install 3.10

      - name: Get new availability data
        run: |
          date_str=$(date +%Y-%m-%d-%H)
          uv run python scripts/get_availability.py --out data/2025/$(date +%Y-%m-%d-%H).csv

      - name: Commit and push to availability branch
        run: |
          date_str=$(date +%Y-%m-%d-%H)
          git config --global user.name 'GitHub Action'
          git config --global user.email 'leonlan@users.noreply.github.com'
          git fetch origin
          git checkout 2025
          git add data/2025/${date_str}.csv
          git commit -m "Add availability ${date_str}"
          git push origin 2025
